services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: mcc
    ports:
      - "5432:5432" # Expose PostgreSQL port
    volumes:
      - db_data:/var/lib/postgresql/data # Persistent data
  web:
    image: node:22-alpine
    container_name: webapp
    working_dir: /app
    volumes:
      - .:/app # Mount the current directory into the container
      - /app/node_modules # Exclude node_modules from being overwritten
    environment:
      - DATABASE_URL=postgresql://db_user:db_password@db:5432/mcc
    ports:
      - "3000:3000" # Expose Next.js on port 3000
    command: sh -c "npm install && npm run dev" # Install dependencies and start dev server
    depends_on:
      - db

volumes:
  db_data:
